version: "3.7"

services:
  redis:
    image: redislabs/rejson:latest
    ports:
      - 6379:6379
    command:
      [
        "redis-server",
        "--loadmodule",
        "/usr/lib/redis/modules/rejson.so",
        "--appendonly",
        "yes",
      ]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis

volumes:
  redis-data:
